# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_ENV = "production"
  SUPABASE_URL = ""
  SUPABASE_SERVICE_ROLE_KEY = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"